# Generated by Django 4.1 on 2022-10-16 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mngadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clgname', models.CharField(max_length=60)),
                ('location', models.CharField(max_length=60)),
            ],
        ),
    ]
