# Generated by Django 4.1 on 2022-10-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mngadmin', '0002_mdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='mcompanyT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=60)),
                ('clocation', models.CharField(max_length=60)),
                ('cvacancy', models.CharField(max_length=60)),
                ('nvacancy', models.IntegerField()),
                ('cdate', models.DateTimeField()),
            ],
        ),
    ]
